language: c

compiler:
  - gcc

env:
  matrix:
    - SBCL_VERSION=1.3.8
    - SBCL_VERSION=1.2.1
    - SBCL_VERSION=1.1.18

install: ./.travis/install.sh

script:
  - autoconf
  - git fetch --all
  - git tag -l
  - ./configure
  - SBCLISP_HOME=$HOME/sbcl/ EMACS=`which emacs` 2>&1 make >output 2>&1 # Limited as SBCL likes to complain and complain and complain ...
  - tail -n 4000 output
