language: c

compiler:
  - gcc

env:
  matrix:
    - SBCL_VERSION=1.2.1

install: ./.travis/install.sh

script:
  - autoconf
  - ./configure
  - SBCLISP_HOME=$HOME/sbcl/ 2>&1 make clean >output 2>&1
  - ls -l ./src/prover/
  - SBCLISP_HOME=$HOME/sbcl/ 2>&1 make >output 2>&1 # Limited as lisp likes to complain and complain and complain ...
  - tail -n 40000 output
